### ISSUE TITLE
Ratel Dashboard post duplicate query and mutate

### ISSUE THREAD

**Issue by LoganLee1991** [dgraph-io/ratel#107] opened 2019-08-26 10:51 UTC
When I click "run" button in the Ratel dashboard console, the mutate (or query) operation will execute two times, which make two nodes added, not one it should be. Is it a bug or any thing i do wrong?

dgraph version: Dgraph v1.0.16, Binaries for Windows
ratel dashboard: Local Bundle version
browser: Firefox 68.0.2
![图片](https://user-images.githubusercontent.com/19644417/63685604-629eb900-c832-11e9-9a8c-da9f13bca714.png)

**Comment by catsalt** [comment] 2019-09-02 10:09
yes, I find that too.. 
when Mutation from the local console.

Dgraph v1.0.17 Windows
Browser, Edge

**Comment by paulftw** [comment] 2019-09-02 16:50
Just tried this on my local instance and could not reproduce the **two nodes added** part.
@LoganLee1991 can you please run a query to confirm that indeed two nodes got added in your system?

Two requests are normal because the first one is CORS pre-flight (HTTP OPTIONS), the second one is the actual request.

Closing this bug because from what's reported in here and based on my test everything's working as expected.
If anyone is still seeing duplicate nodes -- **please re-open**

<img width="1530" alt="mutation" src="https://user-images.githubusercontent.com/769142/64127549-d43eb000-cdba-11e9-9c1c-b21bee26dd20.png">
<img width="1530" alt="query" src="https://user-images.githubusercontent.com/769142/64127558-dacd2780-cdba-11e9-9c0f-01ea11ec7d2f.png">

**Closed by paulftw** 2019-09-02 16:50 UTC

**Comment by LoganLee1991** [comment] 2019-09-03 02:14
I do the same test as you did, and i found two nodes with different uid. 
Thanks for your response. @paulftw 
you can see that same POST request occured when do mutation and query operation.
![图片](https://user-images.githubusercontent.com/19644417/64138789-07238b00-ce31-11e9-8fd4-e9e84b3c1362.png)
![图片](https://user-images.githubusercontent.com/19644417/64138881-85802d00-ce31-11e9-860c-2b90c9415edf.png)
![图片](https://user-images.githubusercontent.com/19644417/64139258-cf1d4780-ce32-11e9-915d-3378843e11b5.png)
