### ISSUE TITLE
Collapse edges by double-click if node is already expanded

### ISSUE THREAD

**Issue by Issif** [dgraph-io/ratel#97] opened 2019-08-06 21:09 UTC
Hi,

It's useful to be able to expand edges of a node by a double click, it might be useful too to collapse them if we double click on an expanded node.

**Comment by paulftw** [comment] 2019-08-13 12:47
Hi, great feature request, but seems to be a duplicate of #50. Closing this one.
Please feel free to re-open if you think you need a different behavior from what's described there.

**Closed by paulftw** 2019-08-13 12:47 UTC
