### ISSUE TITLE
Only one edge is going to be visualized if two nodes have multiple edges to each other.

### ISSUE THREAD

**Issue by svenhartz** [dgraph-io/ratel#176] opened 2020-03-26 13:57 UTC
### How to reproduce
I created three nodes "Michael", "Pawan" and "Leyla". "Michael" is connected to "Leyla" with the `"follows"` **and** the `"is_friend"` edge. "Pawan" is connected to "Leyla" with the `"follows"` edge.

### Observed behavior
I get the following JSON output with my query
```
    "data": {
    "name": [
      {
        "uid": "0x1",
        "name": "Michael",
        "follows": {
          "uid": "0x3",
          "name": "Leyla"
        },
        "is_friend": {
          "uid": "0x3",
          "name": "Leyla"
        }
      },
      {
        "uid": "0x2",
        "name": "Pawan",
        "follows": {
          "uid": "0x3",
          "name": "Leyla"
        }
      },
      {
        "uid": "0x3",
        "name": "Leyla"
      }
    ]
  },
```

The visualization looks like this:

![Screenshot from 2020-03-26 14-50-11](https://user-images.githubusercontent.com/4678346/77654300-30446e00-6f71-11ea-8d0b-9c65f70d6415.png)

So there is only one edge between "Michael" and "Leyla".

### Expected behavior
There should be two edges between Michael" and "Leyla". One "follows" and one "is_friend" edge.

**Comment by MichelDiz** [comment] 2020-04-09 01:45
UPDATE:

I changed the title to make it more accurate.

The problem here is that the Ratel merges all components for a better view of the relationships between all these entities. It turns out that we don't always want to see it that way, we would like to see objects (entities, vertices) even if duplicated with their components independently.

This also affects the Shortest Path. To the point that it is not possible to view all paths found in the query in Graphs. For all the Nodes are merged. And information about Paths is lost. Only possible to check it via inspection of the JSON response.

**Comment by paulftw** [comment] 2020-04-17 12:13
I think original bug -- need for multiple edges is specific and unambiguous. Multiple connections between same two nodes should be visualized.

Second use case -- separating nodes is debatable. We merge nodes into one based on the uid only. This is by design and this reflects the way data is stored in a graph. Lots of use cases depend on this. It sounds like a big and partly related feature request.

I'm going to interpret this bug as the need for multiple arrows, @MichelDiz feel free to file a separate FR with example use case to track the shortest path scenarios.

**Closed** 2020-07-03 14:54 UTC
Labels: kind/enhancement, status/accepted

**Comment by paulftw** [comment] 2020-07-03 15:01
<img width="457" alt="Screen Shot 2020-07-03 at 5 50 34 PM" src="https://user-images.githubusercontent.com/769142/86480674-25129280-bd57-11ea-8c41-91f1ff70c261.png">
