### ISSUE TITLE
ACL incorrectly creates ACL groups.

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#135] opened 2019-10-02 02:04 UTC
Steps to reproduce:

1. Run Dgraph cluster with ACLs enabled
2. Login as groot
3. Add a ACL group called "aGroup"
4. Query for the group with the CLI tool:

```
$ dgraph acl info -g aGroup                   
[Decoder]: Using assembly version of decoder

Running transaction with dgraph endpoint: localhost:9180
Current password for groot:
Login successful.
Unable to show info: The group "aGroup" does not exist.
```

Although Ratel says there's a group, it's not detected via the CLI tool.

@manishrjain and I dug into this a bit and we noticed that the group created via Ratel does not have dgraph.type set to Group for the aGroup node. So it does not exist according to the CLI.

**Comment by paulftw** [comment] 2019-10-03 13:33
Should be fixed, please re-open if not.

Root cause is internals of the ACL have never been documented, and type change is probably a recent addition, because Ratel support for ACL predates the type system

**Closed by paulftw** 2019-10-03 13:33 UTC
Labels: area/commercial/acl, kind/bug, priority/p0
